In [1]:
import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By  # Import for locating elements
from selenium.webdriver.common.keys import Keys  # Import for sending keys
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains

# Phase 1: Get data

## Scrap data

In [67]:
def scrap_workflow(url, driver):
    driver.get(url)
    
    # Utilizar WebDriverWait para esperar a que los elementos se vuelvan visibles
    wait = WebDriverWait(driver, 10)  # Puedes ajustar el tiempo máximo de espera según sea necesario
    
    # Lists to save data
    title = []
    description = []
    level = []
    price = []
    category = []
    date = []
    
    for pages in range(1, 5):
        # Esperar a que los elementos estén presentes
        elements = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "section > article")))
    
        for element in elements:
            
            #element.click()
            
            # Obtener el título
            titleData = element.find_element(By.CSS_SELECTOR, "h2.h4").text
            title.append(titleData)
            
            # Obtener el nivel
            levelData = element.find_element(By.CSS_SELECTOR, "li:nth-child(2) > strong").text
            level.append(levelData)
            
            # Obtener el precio
            priceData = element.find_element(By.CSS_SELECTOR, "strong:nth-child(2)").text
            price.append(priceData)
            
            # Obtener la descripción
            descriptionData = element.find_element(By.CSS_SELECTOR, ".clamp .mb-0").text
            description.append(descriptionData)
            
            # Obtener las categorías
            try:
                categories = element.find_element(By.CSS_SELECTOR, "section.card-list-container > article div.air3-token-container").text
            except NoSuchElementException:
                categories = ""  # Si no se encuentra la categoría, establece NA como valor predeterminado
            category.append(categories)
            
            # Obtener la fecha de publicacion
            dateData = element.find_element(By.CSS_SELECTOR, ".text-light > span:nth-child(2)").text
            date.append(dateData)
            
            #click = driver.find_element(By.CSS_SELECTOR, '.air3-slider-close-desktop svg')
            #click.click()
            #time.sleep(2)
    
        click = driver.find_element(By.CSS_SELECTOR, '*:nth-child(2) > *:nth-child(10) > * > *:nth-child(1)')
        click.click()
    # Cerrar el navegador
    driver.quit()
    
    return title, description, level, price, category, date

In [78]:
# Specify the path to the Chrome driver executable
driver_path = r'chromedriver-win64\chromedriver.exe'

# Create an instance of ChromeOptions
chrome_options = Options()

# Add any desired options
chrome_options.add_argument("--start-maximized")  # Maximize the browser window

# Initialize the webdriver with the options and driver path
service = Service(driver_path)
driver = webdriver.Chrome(service=service, options=chrome_options)

# Obtener el URL del nuevo tab
url = "https://www.upwork.com/search/freelance-jobs/data-science?sort=recency&t=1"

title, description, level, price, category, date = scrap_workflow(url, driver)

NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=118.0.5993.89)
Stacktrace:
	GetHandleVerifier [0x00007FF646478EF2+54786]
	(No symbol) [0x00007FF6463E5612]
	(No symbol) [0x00007FF64629A64B]
	(No symbol) [0x00007FF64627A9F5]
	(No symbol) [0x00007FF646300887]
	(No symbol) [0x00007FF6463143CF]
	(No symbol) [0x00007FF6462FBC43]
	(No symbol) [0x00007FF6462D0941]
	(No symbol) [0x00007FF6462D1B84]
	GetHandleVerifier [0x00007FF6467C7F52+3524194]
	GetHandleVerifier [0x00007FF64681D800+3874576]
	GetHandleVerifier [0x00007FF646815D7F+3843215]
	GetHandleVerifier [0x00007FF646515086+694166]
	(No symbol) [0x00007FF6463F0A88]
	(No symbol) [0x00007FF6463ECA94]
	(No symbol) [0x00007FF6463ECBC2]
	(No symbol) [0x00007FF6463DCC83]
	BaseThreadInitThunk [0x00007FFF26447344+20]
	RtlUserThreadStart [0x00007FFF27E426B1+33]

## Create df and clean data

In [70]:
import pandas as pd
from datetime import datetime

def create_dataframe(title, description, level, price, category, date, job_search):
    # Create date of scrap
    date_scrapped = datetime.now().strftime('%Y-%m-%d')

    # Create dataframe with variables
    df = pd.DataFrame({'id': range(len(title)),
                       'date_scrapped': date_scrapped, 
                       'date_posted': date,
                       'title': title,
                       'description': description,
                       'level': level,
                       'cathegory': category,
                       'price': price,
                       'job_search': job_search
                      })


    # ------------------------------------------------
    # Adjust date_posted to a datetime format
    # ------------------------------------------------
    
    # Create an aux variable to calculate date_posted in datetime format
    df['date_aux'] = df['date_posted'].apply(lambda x: int(x.split('days')[0]) if 'days' in x else 0)
    
    # Leave date_scrapped in datetime format
    df['date_scrapped'] = pd.to_datetime(df['date_scrapped'], format='ISO8601')
    
    # Create date column with datetime date post.
    df['date_post'] = df['date_scrapped'] - pd.to_timedelta(df['date_aux'], unit='D')
    
    # Select only variables to use
    vars = ['id', 'date_scrapped', 'date_post', 'job_search', 'title', 'description', 'level', 'cathegory', 'price']
    df = df[vars]
    
    # ------------------------------------------------
    # Change values in level to 0, 1, 2
    # ------------------------------------------------
    
    # Mapear los valores a 0, 1 y 2
    mapping = {'Entry level': 0, 'Intermediate': 1, 'Expert': 2}
    df['level'] = df['level'].map(mapping)
    
    # ------------------------------------------------
    # Clean cathegory columns
    # ------------------------------------------------
    df['cathegory'] = df['cathegory'].str.replace('\n', ',')
    
    # ------------------------------------------------
    # Clean price column
    # ------------------------------------------------
    
    # Replace '$' and ',' values and leave column as int 
    df['price'] = df['price'].str.replace('$', '')
    df['price'] = df['price'].str.replace(',', '')
    df['price'] = df['price'].astype(int) 
    
    # ------------------------------------------------
    # Rename columns
    # ------------------------------------------------
    df.rename(columns={'description': '_description',
                      'level': '_level'}, inplace=True)
    
    return df

In [73]:
df = create_dataframe(title, description, level, price, category, date, job_search = 'Data scientist') 
df.head()

,id,date_scrapped,date_post,job_search,title,_description,_level,cathegory,price
0,0,2023-10-19,2023-10-19,Data scientist,"Capture, Analyse and Predict with Artificial I...",1. Objective: Identify behavior patterns and p...,1,"Data Visualization,Data Science,Report,Python,...",200
1,1,2023-10-19,2023-10-19,Data scientist,Social Science Research,I need to conduct analysis of data I collected...,1,"Data Analysis,Research Papers,Academic Writing...",60
2,2,2023-10-19,2023-10-19,Data scientist,Share Your Scientific Body Composition & Shape...,We are a non-profit scientific research instit...,0,"Health Science,Science,Communications,Human Bo...",6
3,3,2023-10-19,2023-10-19,Data scientist,"Build No-Code Prototype (Text Scraper, Parser,...","Hi there, I'm looking for an experienced perso...",2,"Data Extraction,Data Science,Data Scraping,Mac...",400
4,4,2023-10-19,2023-10-19,Data scientist,Influencer Partner for Scientific Research,"As a nonprofit scientific research institute, ...",0,"Health Science,Science,Social Media Marketing,...",2000

## Update MySQL table

In [101]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

def update_tableSQL(df, engine):
    
    df_sql = pd.read_sql('upwork_advices', con = engine)
    
    ###################
    # Check for duplicated values in data_scrapped and update table
    ###################
    
    # Find commons values
    commonValues = df_sql.values.flatten()  # Get all data from sql
    
    # Delete commons values in df with df_sql
    df_scrapped = df[~df.isin(commonValues).any(axis=1)]  
    
    ###################
    # Update table 
    df_scrapped.to_sql(name='upwork_advices', con=engine, if_exists='append', index=False)

In [75]:
# Create connection with table
engine = create_engine('mysql+mysqlconnector://root:Bastyan1@192.168.1.95/upwork')

update_tableSQL(df, engine)

## Resulting DF

In [76]:
engine = create_engine('mysql+mysqlconnector://root:Bastyan1@192.168.1.95/upwork')
df_sql = pd.read_sql('upwork_advices', con = engine)
df_sql.head()

,id,date_scrapped,date_post,job_search,title,_description,_level,price,cathegory
0,1,2023-10-19,2023-10-19,Data scientist,Social Science Research,I need to conduct analysis of data I collected...,1,60,"Data Analysis,Research Papers,Academic Writing..."
1,2,2023-10-19,2023-10-19,Data scientist,Share Your Scientific Body Composition & Shape...,We are a non-profit scientific research instit...,0,6,"Health Science,Science,Communications,Human Bo..."
2,3,2023-10-19,2023-10-19,Data scientist,"Build No-Code Prototype (Text Scraper, Parser,...","Hi there, I'm looking for an experienced perso...",2,400,"Data Extraction,Data Science,Data Scraping,Mac..."
3,4,2023-10-19,2023-10-19,Data scientist,Influencer Partner for Scientific Research,"As a nonprofit scientific research institute, ...",0,2000,"Health Science,Science,Social Media Marketing,..."
4,5,2023-10-19,2023-10-19,Data scientist,"AI/ML, Vertex AI, NLP and Python for chatbot a...",Looking to hire someone for a project which re...,2,25,"Data Science,Vertex AI,Python,AI Chatbot,API,L..."

## Workflow

In [93]:
job_search = 'Data Analyst'
url = "https://www.upwork.com/search/freelance-jobs/data-science?category2_uid=531770282580668420&sort=recency&subcategory2_uid=531770282593251330&t=1"

In [105]:
# Specify the path to the Chrome driver executable
driver_path = r'chromedriver-win64\chromedriver.exe'

# Create an instance of ChromeOptions
chrome_options = Options()

# Add any desired options
chrome_options.add_argument("--start-maximized")  # Maximize the browser window

# Initialize the webdriver with the options and driver path
service = Service(driver_path)
driver = webdriver.Chrome(service=service, options=chrome_options)

# Obtener el URL del nuevo tab
url = url

# Scrap data and save it into lists
title, description, level, price, category, date = scrap_workflow(url, driver)

# Clean and create dataframe from data scrapped
df = create_dataframe(title, description, level, price, category, date, job_search) 

# Update tables in MySQL
engine = create_engine('mysql+mysqlconnector://root:Bastyan1@192.168.1.95/upwork')
update_tableSQL(df, engine)

In [100]:
# Show results
engine = create_engine('mysql+mysqlconnector://root:Bastyan1@192.168.1.95/upwork')
df_sql = pd.read_sql('upwork_advices', con = engine)
df_sql.tail()

,id,date_scrapped,date_post,job_search,title,_description,_level,price,cathegory
35,36,2023-10-19,2023-10-17,Data scientist,Experienced Machine Learning Engineer - Health...,We are seeking an experienced Machine Learning...,2,5500,"Data Science,Data Analysis,Machine Learning,Py..."
36,37,2023-10-19,2023-10-17,Data scientist,GoLang developer - Bangalore Hybrid,"1.Backend Development: Design, develop, and ma...",1,1100,"Golang,Software Architecture & Design,API,Mong..."
37,38,2023-10-19,2023-10-17,Data scientist,NLP Model Training,We are looking for an expert in Natural Langua...,2,200,"Data Science,Natural Language Processing,Machi..."
38,39,2023-10-19,2023-10-17,Data scientist,Data Engineer | Full-Time required,We are looking for a Data Engineer with Python...,1,400,"Data Preprocessing,Data Engineering,Data Integ..."
39,41,2023-10-19,2023-10-19,Data scientist,"Capture, Analyse and Predict with Artificial I...",1. Objective: Identify behavior patterns and p...,1,200,"Data Visualization,Data Science,Report,Python,..."

In [ ]:
df_sql.to_csv(r'\data_backup\data_scrapper.csv', index=False)

In [89]:
len(df_sql['job_search'])

40

In [95]:
# Show results
engine = create_engine('mysql+mysqlconnector://root:Bastyan1@192.168.1.95/upwork')
df_sql = pd.read_sql('upwork_advices', con = engine)
df_sql.loc[df_sql['job_search'] == 'Data Analyst']

Empty DataFrame
Columns: [id, date_scrapped, date_post, job_search, title, _description, _level, price, cathegory]
Index: []

# Phase 2: Analyze data

In [55]:
# ------------------------------------------------
# Divide each cathegories in different columns
# ------------------------------------------------

# Dividir la columna 'category' en una lista de categorías
def create_categories(df, var = 'cathegory'):
    
    df[var] = df[var].str.split(',')

    # Crear un DataFrame temporal con las categorías como columnas
    df_temp = df[var].apply(pd.Series)
    
    # Renombrar las columnas agregando un prefijo 'category'
    df_temp = df_temp.rename(lambda x: f'{var}{x + 1}', axis='columns')
    
    # Combinar el DataFrame original con el DataFrame temporal
    df = pd.concat([df, df_temp], axis=1)
    
    # Drop variable that will not use
    df = df.drop(var, axis=1)
    
    return df

In [64]:
df_sql = create_categories(df_sql)
df_sql.head()

,id,date_scrapped,date_post,job_search,title,_description,_level,price,cathegory1,cathegory2,cathegory3,cathegory4,cathegory5,cathegory6,cathegory7,cathegory8,cathegory9,cathegory10
0,1,2023-10-19,2023-10-19,Data scientist,Social Science Research,I need to conduct analysis of data I collected...,1,60,Data Analysis,Research Papers,Academic Writing,Research Methods,Academic Research,NaN,NaN,NaN,NaN,NaN
1,2,2023-10-19,2023-10-19,Data scientist,Share Your Scientific Body Composition & Shape...,We are a non-profit scientific research instit...,0,6,Health Science,Science,Communications,Human Body,Social Media Marketing,Research Interviews,+3,NaN,NaN,NaN
2,3,2023-10-19,2023-10-19,Data scientist,"Build No-Code Prototype (Text Scraper, Parser,...","Hi there, I'm looking for an experienced perso...",2,400,Data Extraction,Data Science,Data Scraping,Machine Learning,Prototyping,Natural Language Processing,Python,NaN,NaN,NaN
3,4,2023-10-19,2023-10-19,Data scientist,Influencer Partner for Scientific Research,"As a nonprofit scientific research institute, ...",0,2000,Health Science,Science,Social Media Marketing,Human Body,Health & Wellness,Health,Health & Fitness,+1,NaN,NaN
4,5,2023-10-19,2023-10-19,Data scientist,"AI/ML, Vertex AI, NLP and Python for chatbot a...",Looking to hire someone for a project which re...,2,25,Data Science,Vertex AI,Python,AI Chatbot,API,LangChain,Structural Analysis & Design Software,+2,NaN,NaN
5,6,2023-10-19,2023-10-19,Data scientist,Recently Lose Weight? Share Your Story,"Did you do the hard work and lose the weight, ...",0,25,Health Science,Digital Marketing,Human Body,Health & Fitness,Health,Video Camera,Video Editing,NaN,NaN,NaN
6,7,2023-10-19,2023-10-19,Data scientist,Scientific Researcher - College Student,Do you have a large group of diverse friends/f...,0,250,Health Science,Science,Science & Medicine,Social Media Marketing,Human Body,Health & Fitness,+4,NaN,NaN,NaN
7,8,2023-10-19,2023-10-19,Data scientist,Influencer for Genetic Body Composition Science,We are looking to partner with an Influencer. ...,0,2000,Science,Health Science,Digital Marketing,Human Body,Health & Fitness,Video Camera,Health & Wellness,+3,NaN,NaN
8,9,2023-10-19,2023-10-19,Data scientist,Share Your Scientific Body Composition Story,We need real people who are interested in talk...,0,200,Science,Human Body,Video Editing,Education,Video Production,Social Media Marketing,Instagram,+2,NaN,NaN
9,10,2023-10-19,2023-10-19,Data scientist,"Diet, Exercise, Lifestyle Health Influencer Co...",Our growing Instagram Account (50K+) needs mor...,0,500,Human Body,Health & Fitness,Health & Wellness,Research Interviews,Instagram,Social Media Marketing,+3,NaN,NaN,NaN
10,11,2023-10-19,2023-10-19,Data scientist,Python Developer - DB Parsing & ML Project,We're in search of a Python Developer for an e...,1,500,Data Science,Data Scraping,Python,Machine Learning,Python Script,PostgreSQL,AI Consulting,NaN,NaN,NaN
11,12,2023-10-19,2023-10-19,Data scientist,Machine Learning model and training,Develop a predictive model using ML for an NLP...,2,600,Data Science,Natural Language Processing,Machine Learning Model,Model Tuning,Chatbot,+5,NaN,NaN,NaN,NaN
12,13,2023-10-19,2023-10-19,Data scientist,Data analysis / Machine Learning Engineer,"Need a working prototype of this theme "" Incre...",1,300,Data Science,Data Analysis,Data Modeling,Machine Learning,Deep Learning,Analytics,deeplearn.js,+1,NaN,NaN
13,14,2023-10-19,2023-10-19,Data scientist,Google Colab Decision Tree,We are looking for a freelancer who can use Go...,1,30,Data Science,Data Analysis,Data Mining,Python,Google Analytics,NaN,NaN,NaN,NaN,NaN
14,15,2023-10-19,2023-10-19,Data scientist,AI/ML Developer for Sports Live Data Prediction,Job Description: Are you a skilled AI/ML devel...,2,2000,Data Science,Data Analysis,Machine Learning,Python,Artificial Intelligence,TensorFlow,Deep Learning,NaN,NaN,NaN
15,16,2023-10-19,2023-10-19,Data scientist,Compensated Interview about Big Data Tools | $...,Hello! We are conducting a compensated study a...,0,250,Data Analysis,Big Data,Data Science,Operations Analytics,Growth Analytics,NaN,NaN,NaN,NaN,NaN
16,17,2023-10-19,2023-10-19,Data scientist,Implementation of a Churn prediction model,#ChurnPrediction #BaselineModel #Python #Snowf...,2,1000,Data Science Consultation,Data Analysis,Data Science,Machine Learning Model,Python,Machine Learning,NaN,NaN,NaN,NaN
17,18,2023-10-19,2023-10-19,Data scientist,Speech Recognition Algorithm Developer for Pro...,Project Overview We are seeking an experienced...,1,2000,Data Science,Machine Learning,Natural Language Processing,Deep Learning,Artificial Intelligence,+1,NaN,NaN,NaN,NaN
18,19,2023-10-19,2023-10-19,Data scientist,Big Data Web Portal Analysis Developer Needed,"Key Responsibilities 1. Design, develop, and i...",2,500,Data Integration,Data Preprocessing,Data Transformation,Database Architecture,Apache Spark,Java,+4,NaN,NaN,NaN
19,20,2023-10-19,2023-10-19,Data scientist,Merge data with ML Classification Algorithm-im...,I have a classification algorithm that is runn...,2,70,Data Science,Machine Learning Model,Model Optimization,Model Tuning,Classification,pandas,Python,+1,NaN,NaN
20,21,2023-10-19,2023-10-19,Data scientist,Find relevant participants for online hackathon,MORE INFORMATION ABOUT AGORIZE AT THE END OF T...,0,3000,Contact List,Market Research,Lead Generation,Lead Capture,NaN,NaN,NaN,NaN,NaN,NaN
21,22,2023-10-19,2023-10-19,Data scientist,Building ARIMA Model Using R,"Hello, I need a talented analyst who can work ...",1,40,Data Science,Data Analysis,R,Statistics,Python,Machine Learning,ggplot2,Econometrics,+2,NaN
22,23,2023-10-19,2023-10-19,Data scientist,Python Signal Analyzer,We are looking for a skilled Python developer ...,1,200,Data Science,Data Analysis,Python,Machine Learning,C++,NaN,NaN,NaN,NaN,NaN
23,24,2023-10-19,2023-10-19,Data scientist,Android + IOS Developer,We are looking for Android and IOS Developer w...,1,150,Smartphone,Android,iOS,Mobile App Development,iOS Development,User Authentication,+2,NaN,NaN,NaN
24,25,2023-10-19,2023-10-19,Data scientist,Full Stack Python Application Development,Main functionality required: AI/ML and Data An...,0,30,Java,Kotlin,JavaScript,Android,iOS,Smartphone,Web Development,Android App Development,+2,NaN
25,26,2023-10-19,2023-10-19,Data scientist,Senior AI/ML Consultant,Following our successful integration of Genera...,2,2000,GPT-4,Generative AI,Azure OpenAI Service,Large Language Model,Machine Learning,Artificial Intelligence,NaN,NaN,NaN,NaN
26,27,2023-10-19,2023-10-19,Data scientist,Embedded Systems Expert for Data Analysis and ...,"I am really happy to write you back. So, I am ...",2,90,Data Science,Data Analysis,Python,Machine Learning,Embedded System,NaN,NaN,NaN,NaN,NaN
27,28,2023-10-19,2023-10-19,Data scientist,Embedded Systems Expert for Data Analysis and ...,"I am really happy to write you back. So, I am ...",2,90,Data Science,Data Analysis,Machine Learning Model,Computer Vision,Python,PyQt,Thermodynamics,+3,NaN,NaN
28,29,2023-10-19,2023-10-19,Data scientist,Use R to analyze pictures and identify areas o...,I will provide pictures for training the model...,1,100,Data Science,R,Machine Learning,Python,NaN,NaN,NaN,NaN,NaN,NaN
29,30,2023-10-19,2023-10-19,Data scientist,Content Writer Required - Python & Tableau & G...,I'm looking for a content writter who can prep...,1,5,Data Science,Tableau,Dashboard,Python,Content Creation,NaN,NaN,NaN,NaN,NaN
30,31,2023-10-19,2023-10-19,Data scientist,Web development for startup sports data scienc...,Looking for: Fullstack developer I am looking ...,1,1000,API Integration,Python,Web Design,Web Development,JavaScript,CSS,HTML,NaN,NaN,NaN
31,32,2023-10-19,2023-10-19,Data scientist,NET Developer,We are seeking a highly skilled and motivated ...,1,6,.NET Framework,ASP.NET,C#,ASP.NET MVC,API,Microsoft SQL Server,SQL,JavaScript,jQuery,+1
32,33,2023-10-19,2023-10-19,Data scientist,Improve my machine learning algorithm,I have a large dataset that I am looking to tr...,2,75,Data Science,Machine Learning,Python,Deep Learning,TensorFlow,NaN,NaN,NaN,NaN,NaN
33,34,2023-10-19,2023-10-19,Data scientist,Development of Artificial Intelligence Algorit...,I am looking for a software developer/data ana...,1,800,Data Science,Data Analysis,Python,Machine Learning,Artificial Intelligence,MATLAB,Deep Learning,+3,NaN,NaN
34,35,2023-10-19,2023-10-19,Data scientist,Data Science - Statistics Cost Distribution An...,"Hello, In python, i need statistical analysis ...",2,250,Data Analysis,Data Science,Data Modeling,Statistics,Quantitative Analysis,Python,Statistical Analysis,NaN,NaN,NaN
35,36,2023-10-19,2023-10-17,Data scientist,Experienced Machine Learning Engineer - Health...,We are seeking an experienced Machine Learning...,2,5500,Data Science,Data Analysis,Machine Learning,Python,Survival Analysis,NaN,NaN,NaN,NaN,NaN
36,37,2023-10-19,2023-10-17,Data scientist,GoLang developer - Bangalore Hybrid,"1.Backend Development: Design, develop, and ma...",1,1100,Golang,Software Architecture & Design,API,MongoDB,Database,NaN,NaN,NaN,NaN,NaN
37,38,2023-10-19,2023-10-17,Data scientist,NLP Model Training,We are looking for an expert in Natural Langua...,2,200,Data Science,Natural Language Processing,Machine Learning,Python,Deep Learning,NaN,NaN,NaN,NaN,NaN
38,39,2023-10-19,2023-10-17,Data scientist,Data Engineer | Full-Time required,We are looking for a Data Engineer with Python...,1,400,Data Preprocessing,Data Engineering,Data Integration,Python,ETL Pipeline,API,FastAPI,Web Scraping,NaN,NaN
39,41,2023-10-19,2023-10-19,Data scientist,"Capture, Analyse and Predict with Artificial I...",1. Objective: Identify behavior patterns and p...,1,200,Data Visualization,Data Science,Report,Python,Artificial Intelligence,Machine Learning,NaN,NaN,NaN,NaN

# Phase 3: Create Dashboard