In [10]:
import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By  # Import for locating elements
from selenium.webdriver.common.keys import Keys  # Import for sending keys
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains

# Scrap data

In [16]:
# Specify the path to the Chrome driver executable
driver_path = r'\workspaces\upWork_scrap\chromedriver-win64\chromedriver.exe'

# Create an instance of ChromeOptions
chrome_options = Options()

# Add any desired options
chrome_options.add_argument("--start-maximized")  # Maximize the browser window

# Initialize the webdriver with the options and driver path
service = Service(driver_path)
driver = webdriver.Chrome(service=service, options=chrome_options)

# Obtener el URL del nuevo tab
url = "https://www.upwork.com/search/freelance-jobs/data-science?sort=recency&t=1"
driver.get(url)

# Utilizar WebDriverWait para esperar a que los elementos se vuelvan visibles
wait = WebDriverWait(driver, 10)  # Puedes ajustar el tiempo máximo de espera según sea necesario

# Lists to save data
title = []
description = []
level = []
price = []
category = []
date = []

for pages in range(1, 5):
    # Esperar a que los elementos estén presentes
    elements = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "section > article")))

    for element in elements:
        
        #element.click()
        
        # Obtener el título
        titleData = element.find_element(By.CSS_SELECTOR, "h2.h4").text
        title.append(titleData)
        
        # Obtener el nivel
        levelData = element.find_element(By.CSS_SELECTOR, "li:nth-child(2) > strong").text
        level.append(levelData)
        
        # Obtener el precio
        priceData = element.find_element(By.CSS_SELECTOR, "strong:nth-child(2)").text
        price.append(priceData)
        
        # Obtener la descripción
        descriptionData = element.find_element(By.CSS_SELECTOR, ".clamp .mb-0").text
        description.append(descriptionData)
        
        # Obtener las categorías
        try:
            categories = element.find_element(By.CSS_SELECTOR, "section.card-list-container > article div.air3-token-container").text
        except NoSuchElementException:
            categories = ""  # Si no se encuentra la categoría, establece NA como valor predeterminado
        category.append(categories)
        
        # Obtener la fecha de publicacion
        dateData = element.find_element(By.CSS_SELECTOR, ".text-light > span:nth-child(2)").text
        date.append(dateData)
        
        #click = driver.find_element(By.CSS_SELECTOR, '.air3-slider-close-desktop svg')
        #click.click()
        #time.sleep(2)

    click = driver.find_element(By.CSS_SELECTOR, '*:nth-child(2) > *:nth-child(10) > * > *:nth-child(1)')
    click.click()
# Cerrar el navegador
driver.quit()

NoSuchDriverException: Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

# Create df and clean data

In [105]:
import pandas as pd
from datetime import datetime

# Create date of scrap
date_scrapped = datetime.now().strftime('%Y-%m-%d')

# Create dataframe with variables
df = pd.DataFrame({'id': range(len(title)),
                   'date_scrapped': date_scrapped, 
              'date_posted': date,
              'title': title,
              'description': description,
              'level': level,
              'category_qty': category_len,
              'category': category,
              'price': price,
              'job_search': 'Data scientist'
})


# ------------------------------------------------
# Adjust date_posted to a datetime format
# ------------------------------------------------

# Create an aux variable to calculate date_posted in datetime format
df['date_aux'] = df['date_posted'].apply(lambda x: int(x.split('days')[0]) if 'days' in x else 0)

# Leave date_scrapped in datetime format
df['date_scrapped'] = pd.to_datetime(df['date_scrapped'], format='ISO8601')

# Create date column with datetime date post.
df['date_post'] = df['date_scrapped'] - pd.to_timedelta(df['date_aux'], unit='D')

# Select only variables to use
vars = ['id', 'date_scrapped', 'date_post', 'job_search', 'title', 'description', 'level', 'category_qty', 'category', 'price']
df = df[vars]

# ------------------------------------------------
# Create cathegory dataframe by id and date post
# ------------------------------------------------

# ------------------------------------------------
# Divide each cathegories in different columns
# ------------------------------------------------

# Dividir la columna 'category' en una lista de categorías
df['category'] = df['category'].str.split('\n')

# Crear un DataFrame temporal con las categorías como columnas
df_temp = df['category'].apply(pd.Series)

# Renombrar las columnas agregando un prefijo 'category'
df_temp = df_temp.rename(lambda x: f'cathegory{x + 1}', axis='columns')

# Combinar el DataFrame original con el DataFrame temporal
df = pd.concat([df, df_temp], axis=1)

# Drop variable that will not use
df = df.drop('category', axis=1)

# ------------------------------------------------
# Change values in level to 0, 1, 2
# ------------------------------------------------

# Mapear los valores a 0, 1 y 2
mapping = {'Entry level': 0, 'Intermediate': 1, 'Expert': 2}
df['level'] = df['level'].map(mapping)

# ------------------------------------------------
# Clean price column
# ------------------------------------------------

# Replace $ value and leave as float 
df['price'] = df['price'].str.replace('$', '')
df['price'] = df['price'].astype(float)

In [106]:
df

,id,date_scrapped,date_post,job_search,title,description,level,category_qty,price,cathegory1,cathegory2,cathegory3,cathegory4,cathegory5,cathegory6,cathegory7,cathegory8,cathegory9,cathegory10
0,0,2023-10-19,2023-10-19,Data scientist,Share Your Scientific Body Composition & Shape...,We are a non-profit scientific research instit...,0,40,$6,Health Science,Science,Communications,Human Body,Social Media Marketing,Research Interviews,+3,NaN,NaN,NaN
1,1,2023-10-19,2023-10-19,Data scientist,Senior AI/ML Consultant,Following our successful integration of Genera...,2,40,"$2,000",GPT-4,Generative AI,Azure OpenAI Service,Large Language Model,Machine Learning,Artificial Intelligence,NaN,NaN,NaN,NaN
2,2,2023-10-19,2023-10-19,Data scientist,Embedded Systems Expert for Data Analysis and ...,"I am really happy to write you back. So, I am ...",2,40,$90,Data Science,Data Analysis,Python,Machine Learning,Embedded System,NaN,NaN,NaN,NaN,NaN
3,3,2023-10-19,2023-10-19,Data scientist,Embedded Systems Expert for Data Analysis and ...,"I am really happy to write you back. So, I am ...",2,40,$90,Data Science,Data Analysis,Machine Learning Model,Computer Vision,Python,PyQt,Thermodynamics,+3,NaN,NaN
4,4,2023-10-19,2023-10-19,Data scientist,Use R to analyze pictures and identify areas o...,I will provide pictures for training the model...,1,40,$100,Data Science,R,Machine Learning,Python,NaN,NaN,NaN,NaN,NaN,NaN
5,5,2023-10-19,2023-10-19,Data scientist,Content Writer Required - Python & Tableau & G...,I'm looking for a content writter who can prep...,1,40,$5,Data Science,Tableau,Dashboard,Python,Content Creation,NaN,NaN,NaN,NaN,NaN
6,6,2023-10-19,2023-10-19,Data scientist,Influencer Partner for Scientific Research,"As a nonprofit scientific research institute, ...",0,40,"$2,000",Health Science,Science,Social Media Marketing,Human Body,Health & Wellness,Health,Health & Fitness,+1,NaN,NaN
7,7,2023-10-19,2023-10-19,Data scientist,Web development for startup sports data scienc...,Looking for: Fullstack developer I am looking ...,1,40,"$1,000",API Integration,Python,Web Design,Web Development,JavaScript,CSS,HTML,NaN,NaN,NaN
8,8,2023-10-19,2023-10-19,Data scientist,NET Developer,We are seeking a highly skilled and motivated ...,1,40,$6,.NET Framework,ASP.NET,C#,ASP.NET MVC,API,Microsoft SQL Server,SQL,JavaScript,jQuery,+1
9,9,2023-10-19,2023-10-19,Data scientist,Recently Lose Weight? Share Your Story,"Did you do the hard work and lose the weight, ...",0,40,$25,Health Science,Digital Marketing,Human Body,Health & Fitness,Health,Video Camera,Video Editing,NaN,NaN,NaN
10,10,2023-10-19,2023-10-19,Data scientist,Scientific Researcher - College Student,Do you have a large group of diverse friends/f...,0,40,$250,Health Science,Science,Science & Medicine,Social Media Marketing,Human Body,Health & Fitness,+4,NaN,NaN,NaN
11,11,2023-10-19,2023-10-19,Data scientist,Influencer for Genetic Body Composition Science,We are looking to partner with an Influencer. ...,0,40,"$2,000",Science,Health Science,Digital Marketing,Human Body,Health & Fitness,Video Camera,Health & Wellness,+3,NaN,NaN
12,12,2023-10-19,2023-10-19,Data scientist,Share Your Scientific Body Composition Story,We need real people who are interested in talk...,0,40,$200,Science,Human Body,Video Editing,Education,Video Production,Social Media Marketing,Instagram,+2,NaN,NaN
13,13,2023-10-19,2023-10-19,Data scientist,"Diet, Exercise, Lifestyle Health Influencer Co...",Our growing Instagram Account (50K+) needs mor...,0,40,$500,Human Body,Health & Fitness,Health & Wellness,Research Interviews,Instagram,Social Media Marketing,+3,NaN,NaN,NaN
14,14,2023-10-19,2023-10-19,Data scientist,Improve my machine learning algorithm,I have a large dataset that I am looking to tr...,2,40,$75,Data Science,Machine Learning,Python,Deep Learning,TensorFlow,NaN,NaN,NaN,NaN,NaN
15,15,2023-10-19,2023-10-19,Data scientist,Development of Artificial Intelligence Algorit...,I am looking for a software developer/data ana...,1,40,$800,Data Science,Data Analysis,Python,Machine Learning,Artificial Intelligence,MATLAB,Deep Learning,+3,NaN,NaN
16,16,2023-10-19,2023-10-19,Data scientist,Data Science - Statistics Cost Distribution An...,"Hello, In python, i need statistical analysis ...",2,40,$250,Data Analysis,Data Science,Data Modeling,Statistics,Quantitative Analysis,Python,Statistical Analysis,NaN,NaN,NaN
17,17,2023-10-19,2023-10-19,Data scientist,Experienced Machine Learning Engineer - Health...,We are seeking an experienced Machine Learning...,2,40,"$5,500",Data Science,Data Analysis,Machine Learning,Python,Survival Analysis,NaN,NaN,NaN,NaN,NaN
18,18,2023-10-19,2023-10-19,Data scientist,GoLang developer - Bangalore Hybrid,"1.Backend Development: Design, develop, and ma...",1,40,"$1,100",Golang,Software Architecture & Design,API,MongoDB,Database,NaN,NaN,NaN,NaN,NaN
19,19,2023-10-19,2023-10-19,Data scientist,BigData Engineer,Role : #BigData #Engineer Experience: Must hav...,2,40,"$1,441",Data Engineering,Data Science,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20,2023-10-19,2023-10-19,Data scientist,Big Data Engineer,Role : #BigData #Engineer Experience: Must hav...,2,40,"$1,441",Data Engineering,Big Data,Data Science,Scaled Agile Framework,Apache Hadoop,NaN,NaN,NaN,NaN,NaN
21,21,2023-10-19,2023-10-19,Data scientist,NLP Model Training,We are looking for an expert in Natural Langua...,2,40,$200,Data Science,Natural Language Processing,Machine Learning,Python,Deep Learning,NaN,NaN,NaN,NaN,NaN
22,22,2023-10-19,2023-10-19,Data scientist,Data Engineer | Full-Time required,We are looking for a Data Engineer with Python...,1,40,$400,Data Preprocessing,Data Engineering,Data Integration,Python,ETL Pipeline,API,FastAPI,Web Scraping,NaN,NaN
23,23,2023-10-19,2023-10-19,Data scientist,Looking for - Technical Architect,Experience (Min) : 10.0 Years Experience (Max)...,2,40,"$10,000",Data Integration,SQL,Python,Erwin,NaN,NaN,NaN,NaN,NaN,NaN
24,24,2023-10-19,2023-10-19,Data scientist,Data cleaning task for AI and Machine Learning,A dataset will be provided. The dataset contai...,1,40,$30,Data Science,Data Analysis,Machine Learning,Python,Artificial Intelligence,Python Scikit-Learn,+2,NaN,NaN,NaN
25,25,2023-10-19,2023-10-19,Data scientist,Find 1000 copyright free nice looking images f...,I need help looking for images that are copyri...,1,40,$20,Data Entry,Science,Agriculture,Biology,English,Adobe Photoshop,Botany,Agriculture & Mining,+1,NaN
26,26,2023-10-19,2023-10-19,Data scientist,Machine learning to give stock market buy/sell...,"I have data on daily stock highest price, lowe...",1,40,$100,Data Analysis,Data Science,Python,Machine Learning,Artificial Intelligence,NaN,NaN,NaN,NaN,NaN
27,27,2023-10-19,2023-10-19,Data scientist,Android + IOS Developer,We are looking for Android and IOS Developer w...,1,40,$150,Smartphone,Android,iOS,Mobile App Development,iOS Development,User Authentication,+2,NaN,NaN,NaN
28,28,2023-10-19,2023-10-19,Data scientist,AI Voice Analysis,We're on a mission to create a cutting-edge AI...,2,40,$300,Data Science,Artificial Intelligence,Machine Learning,Natural Language Processing,Deep Learning,+5,NaN,NaN,NaN,NaN
29,29,2023-10-19,2023-10-19,Data scientist,AI & Blockchain Engineers for a show casing pr...,Searching for Expert AI & Blockchain Engineers...,2,40,"$30,000",Data Science,Machine Learning,Python,Artificial Intelligence,Neural Network,Deep Learning,+3,NaN,NaN,NaN
30,30,2023-10-19,2023-10-19,Data scientist,Azure Technical Architect - MDM/ETL,Bachelor’s degree in the field of computer sci...,2,40,"$8,000",Data Engineering,SQL,Python,Microsoft Azure,ETL Pipeline,Erwin,API,GitHub,Jenkins,NaN
31,31,2023-10-19,2023-10-19,Data scientist,Technical Architect,Job Description : Role: Azure Technical Archit...,2,40,"$25,000",Data Integration,SQL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,32,2023-10-19,2023-10-19,Data scientist,Expert in Azure Machine Learning Needed to Ass...,"Hi All, I am currently enrolled in a course on...",2,40,$100,Data Science,Machine Learning Model,Model Optimization,Model Tuning,Microsoft Azure,Machine Learning,+2,NaN,NaN,NaN
33,33,2023-10-19,2023-10-19,Data scientist,I need a full stack programmer to work with me...,I've project that need to me modified in term ...,2,40,$50,Data Science,Python,Algorithm Development,Machine Learning,NaN,NaN,NaN,NaN,NaN,NaN
34,34,2023-10-19,2023-10-19,Data scientist,Applying Bayesian inference to my soil ferilit...,"Hello,I have a dataset (dataset1.csv) attached...",1,40,$50,Data Science,Data Analysis,PyMC,Model Optimization,Bayesian Statistics,Statistics,Machine Learning,+2,NaN,NaN
35,35,2023-10-19,2023-10-19,Data scientist,Classification and Ranking of docs/images/vide...,Hello We want to be able to build a system tha...,2,40,$500,Data Science,Machine Learning,Deep Learning,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,36,2023-10-19,2023-10-19,Data scientist,Buying smart CV parsing solution,"Looking to buy a working CV parsing solution, ...",2,40,"$20,000",Data Science,Machine Learning Model,Artificial Neural Network,Convolutional Neural Network,+6,NaN,NaN,NaN,NaN,NaN
37,37,2023-10-19,2023-10-19,Data scientist,AI and Machine learning expert to optimize Ai ...,We provide a CV assessment and optimization se...,2,40,$200,Data Science,Chatbot,Deep Learning,ChatGPT,Artificial Intelligence,Machine Learning,TensorFlow,+2,NaN,NaN
38,38,2023-10-19,2023-10-19,Data scientist,Build FOREX TRADING course,So I am looking for a full Forex course to be ...,2,40,$50,Data Science,Forex Trading,MQL 4,MetaTrader 4,Financial Analysis,Forecasting,Financial Modeling,NaN,NaN,NaN
39,39,2023-10-19,2023-10-19,Data scientist,Machine Learning Algorithm for NASCAR Race Pre...,We are looking for a skilled machine learning ...,2,40,$400,Data Science,Machine Learning,Python,Deep Learning,TensorFlow,NaN,NaN,NaN,NaN,NaN

# Update MySQL table

In [ ]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

# Create connection with table
engine = create_engine('mysql+mysqlconnector://root:Bastyan1@192.168.1.95/upwork')
df_sql = pd.read_sql('upwork_advices', con = engine)


###################
# Check for duplicated 
# values in data_scrapped
###################

# Find commons values
commonValues = df_sql.values.flatten()  # Get all data from sql

# Delete commons values in df with df_sql
df_scrapped = df[~df.isin(commonValues).any(axis=1)]  

###################
# Update table 
###################

# Insert the DataFrame into the database
df_scrapped.to_sql(name='upwork_advices', con=engine, if_exists='append', index=False)